from typing import Optional
from fastapi import status
"""
nexus-live-entity-verification — CrewAI Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.crewai_tool import VerifyEntityExistenceCrossSignalTool

    @agent
    class MyAgent(Agent):
        tools = [VerifyEntityExistenceCrossSignalTool()]
"""

from typing import Any
from crewai_tools import BaseTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class VerifyEntityExistenceCrossSignalInput(BaseModel):
    domain: str = Field(..., description="Fully qualified domain name to verify, e.g. 'acme-corp.com'. Must be valid IDNA or punycode ASCII.")
    entity_name: str = Field(..., description='Human-readable entity name the domain is supposed to represent, used to anchor registrar, CT, and DNS context. If empty, the tool returns a validation error.')
    min_confidence_threshold: float = Field(None, description="Minimum verdict_confidence required to return a decisive verdict. Below this threshold the tool returns fail-closed 'insufficient_corroboration' in failure_mode_classification. Range 0.0 to 1.0.")
    signal_mask: list[str] = Field(None, description="Optional subset of signals to evaluate from ['whois','ct','wayback','dns']. If omitted or null, all four are evaluated. Do not use to force a verdict when a signal is known to be unavailable; missing signals are reported in signals_missing.")


class VerifyEntityExistenceCrossSignalTool(BaseTool):
    name: str = "nexus_live_entity_verification_verify_entity_existence_cross_signal"
    description: str = 'Fuses WHOIS registration timeline, Certificate Transparency log presence, Wayback Machine snapshot density, and DNS operational maturity with Bayesian calibrated weights to return a corroborated existence verdict, hallucination probability, and failure mode classification. Use when you need a single cross-signal verdict for a named entity and domain pair, especially to detect LLM-hallucinated entities. Do NOT use for live uptime or reachability checks of currently responding services, for domains already known to be registered and DNS-resolving, or when you need raw provider data without cross-signal weighting.'
    args_schema: type[BaseModel] = VerifyEntityExistenceCrossSignalInput

    def _run(self, domain, entity_name, min_confidence_threshold, signal_mask) -> Any:
        return call_mcp_tool("nexus_live_entity_verification_verify_entity_existence_cross_signal", {"domain": domain, "entity_name": entity_name, "min_confidence_threshold": min_confidence_threshold, "signal_mask": signal_mask})

class ResolveWhoisRegistrationTimelineInput(BaseModel):
    domain: str = Field(..., description="Fully qualified domain name to query, e.g. 'acme-corp.com'. Must be valid IDNA or punycode ASCII.")
    include_historical_registrants: bool = Field(None, description='When true, resolves historical registrant records where available. When false, only the current registrant summary is returned to minimize latency and rate-limit exposure.')


class ResolveWhoisRegistrationTimelineTool(BaseTool):
    name: str = "nexus_live_entity_verification_resolve_whois_registration_timeline"
    description: str = "Resolves a domain's WHOIS registration timeline including creation date, expiration date, last updated date, registrar, registrant country, historical registrant count, age in days, and registration gaps. Use when you need to distinguish a legitimately new domain with a coherent timeline from a hallucinated or fabricated one with no WHOIS record or a redacted/broken timeline. Do NOT use for WHOIS privacy law compliance checks, for live DNS reachability status, or when you need RDAP-specific fields not guaranteed by legacy WHOIS."
    args_schema: type[BaseModel] = ResolveWhoisRegistrationTimelineInput

    def _run(self, domain, include_historical_registrants) -> Any:
        return call_mcp_tool("nexus_live_entity_verification_resolve_whois_registration_timeline", {"domain": domain, "include_historical_registrants": include_historical_registrants})

class ProbeCertificateTransparencyPresenceInput(BaseModel):
    domain: str = Field(..., description="Fully qualified domain name to probe, e.g. 'acme-corp.com'. Must be valid IDNA or punycode ASCII.")
    include_subdomains: bool = Field(None, description='When true, includes certificates issued to subdomains of the queried domain. When false, only exact domain matches are analyzed.')
    max_certs_to_analyze: float = Field(None, description='Maximum number of certificate records to analyze from CT logs. Lower values reduce latency but may miss continuity signals. Range 1 to 1000.')


class ProbeCertificateTransparencyPresenceTool(BaseTool):
    name: str = "nexus_live_entity_verification_probe_certificate_transparency_presence"
    description: str = 'Searches Certificate Transparency logs for certificates issued for a domain, computing certificate count, earliest and latest issuance dates, unique issuers, subdomain count, and a continuity score. Use when you need cryptographic evidence of operational TLS issuance, a strong signal against entity hallucination. Do NOT use for certificate content or private key handling, for checking current TLS certificate validity or expiry on a live endpoint, or when you require real-time CT log streaming.'
    args_schema: type[BaseModel] = ProbeCertificateTransparencyPresenceInput

    def _run(self, domain, include_subdomains, max_certs_to_analyze) -> Any:
        return call_mcp_tool("nexus_live_entity_verification_probe_certificate_transparency_presence", {"domain": domain, "include_subdomains": include_subdomains, "max_certs_to_analyze": max_certs_to_analyze})

class MeasureWaybackSnapshotDensityInput(BaseModel):
    domain: str = Field(..., description="Fully qualified domain name to query, e.g. 'acme-corp.com'. Must be valid IDNA or punycode ASCII.")
    lookback_years: float = Field(None, description='Number of years back from the current date to analyze snapshot density. Range 1 to 30.')


class MeasureWaybackSnapshotDensityTool(BaseTool):
    name: str = "nexus_live_entity_verification_measure_wayback_snapshot_density"
    description: str = 'Measures Internet Archive Wayback Machine CDX snapshot density for a domain over a lookback window, returning total snapshots, first and last snapshot dates, snapshots per year, a density score, and coverage gaps in months. Use when distinguishing a long-lived archived domain from a hallucinated one with no archival footprint, or to establish temporal consistency. Do NOT use for retrieving archived page content, for CDX pagination beyond the analyzed window, or when the Internet Archive CDX API is known to be down.'
    args_schema: type[BaseModel] = MeasureWaybackSnapshotDensityInput

    def _run(self, domain, lookback_years) -> Any:
        return call_mcp_tool("nexus_live_entity_verification_measure_wayback_snapshot_density", {"domain": domain, "lookback_years": lookback_years})

class AuditDnsOperationalMaturityInput(BaseModel):
    domain: str = Field(..., description="Fully qualified domain name to audit, e.g. 'acme-corp.com'. Must be valid IDNA or punycode ASCII.")
    resolvers: list[str] = Field(None, description="Optional list of DNS resolver IPs or hosts to query. If omitted or null, defaults to ['8.8.8.8','1.1.1.1']. Maximum 5 resolvers supported per call.")


class AuditDnsOperationalMaturityTool(BaseTool):
    name: str = "nexus_live_entity_verification_audit_dns_operational_maturity"
    description: str = 'Queries DNS resolvers for MX, SPF, DMARC, DKIM selectors, NS record count, and propagation consistency across resolvers, producing a maturity score and signal weight for entity verification. Use when you need to assess whether a domain has been configured for real email and DNS operation, a strong signal that the entity existed and operated beyond mere registration. Do NOT use for checking current DNS resolution failures as a pure monitoring alert, for DNSSEC chain validation, or when you are not prepared for a resolver to be unreachable because it will be reported in signals_missing.'
    args_schema: type[BaseModel] = AuditDnsOperationalMaturityInput

    def _run(self, domain, resolvers) -> Any:
        return call_mcp_tool("nexus_live_entity_verification_audit_dns_operational_maturity", {"domain": domain, "resolvers": resolvers})